### ISSUE TITLE
워크스페이스 목록 

### ISSUE THREAD

**Issue by sungeunnn** [Daon-sy/daon-frontend#66]
- Title
- 워크스페이스 카드
- 워크스페이스 카드 Wrapper
![image](https://github.com/Daon-sy/daon-frontend/assets/109890241/a86ee5f9-136c-4143-9300-14da29eeb3a1)
워크스페이스 카드 Wrapper의 경우, 워크스페이스 목록 뿐 아니라 프로젝트 목록에서도 사용되는 컴포넌트라 공통으로 뽑는건 어떨까싶어 TitleWrapper로 네이밍하였습니다

**Comment by hi0yoo** [comment]
- 워크스페이스 목록 페이지는, 로고 버튼 경로 결정 후 삭제
